### PR TITLE
Updating CoC contact info and all chapter members have reviews and …

### LINKED ISSUE #2: Review the Code of Conduct
We've provided a draft Code of Conduct for you that includes the contact information you provided for reporting purposes. Please ensure that these contact details are correct.

Please close this issue after  **all** chapter organizers have reviewed the CoC thoroughly and confirmed they are comfortable enforcing it.

(This will need to be done before we can list your chapter on our website.)

**Optional:** Our tutorials are currently all in English, but If you decide that you'll be conducting your chapter events and repo discussions in a language other than English, you are welcome to update your Code of Conduct to the appropriate language. What's used right now is a custom Code of Conduct that mixes the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct) ([see available translations](https://www.contributor-covenant.org/translations)) with the [Conference Code of Conduct](http://confcodeofconduct.com/) ([see available translations](https://github.com/confcodeofconduct/confcodeofconduct.com)) to ensure it covers interactions both online and at events.

### PR DESCRIPTION
**Pull request by joshua-ne**
…are comfortable enforcing the CoC Fixes #2

### CODE REVIEW

**Comment by terichadbourne** [comment]
@junyaoren Looks good, and no need to have me merge pull requests for you. You should have those admin privileges to go ahead. Let me know if you run into any issues!

**Comment by joshua-ne** [comment]
> @junyaoren Looks good, and no need to have me merge pull requests for you. You should have those admin privileges to go ahead. Let me know if you run into any issues!

@terichadbourne It seems that I don't have to write access yet. It shows "This branch has no conflicts with the base branch  Only those with write access to this repository can merge pull requests." on my end. 

When I tried to push my commit from a terminal, it says: 
ERROR: Permission to ProtoSchool/xiamen.git denied to junyaoren.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Please help or suggest, thank you very much!

**Comment by terichadbourne** [comment]
@junyaoren It looks like you haven't yet accepted the invite to be an admin. Can you please go to https://github.com/ProtoSchool/xiamen/invitations and take care of that, then try again? (You'll need to enable two-factor authentication on your Github account if you haven't already done that.)

**Comment by joshua-ne** [comment]
@terichadbourne Got it! Thanks!

**Pull request merged**
